name: base
channels:
  - conda-forge
dependencies:
  - r-tidyverse
  - r-docopt
  - r-gdata 
  - r-GGally
  - r-cowplot
  - r-reshape
  - r-tidymodels
  - r-kknn
  - r-testthat
  - r-devtools
  - r-shiny
  - r-usethis
  - r-vdiffr
  - r-bookdown
  - r-knitr
