name: base
channels:
  - conda-forge
dependencies:
  - r-tidyverse=1.3.1
  - r-docopt=0.7.1
  - r-gdata=2.18.0
  - r-GGally=2.1.2
  - r-cowplot=1.1.1
  - r-reshape=0.8.8
  - r-tidymodels=0.1.4
  - r-kknn=1.3.1
  - r-testthat=3.1.2
  - r-devtools=2.4.3
  - r-shiny=1.7.1
  - r-usethis=2.1.5
  - r-vdiffr=1.0.4
  - r-bookdown=0.25
  - r-knitr=1.37
