name: base
channels:
  - conda-forge
dependencies:
  - r-ggplot2=3.3.5
  - r-purrr=0.3.4
  - r-tibble=3.1.6 
  - r-dplyr=1.0.7
  - r-tidyr=1.1.4
  - r-stringr=1.4.0
  - r-readr=2.1.1
  - r-forcats 0.5.1
  - r-broom=0.7.11
  - r-rsample=0.1.1
  - r-dials=0.0.10
  - r-tune=0.1.6
  - r-infer=1.0.0
  - r-workflows=0.2.4
  - r-modeldata=0.1.1
  - r-workflowsets=0.1.0
  - r-parsnip=0.1.7
  - r-yardstick=0.0.9
  - r-recipes=0.1.17 
  - r-testthat=3.1.2
  - r-cowplot=1.1.1
  - r-devtools=2.4.3
  - r-kknn=1.3.1
  - r-scales=1.1.1
  - r-shiny=1.7.1
  - r-tidymodels=0.1.4
  - r-tidyverse=1.3.1
  - r-tinytex=0.37
  - r-usethis=2.1.5
  - r-vdiffr=1.0.2
  - r-vroom=1.5.7

  

    
